# Generated by Django 3.2.8 on 2022-01-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, verbose_name='نام نقش')),
                ('role_permission', models.CharField(blank=True, choices=[('admin', 'ادمین')], max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش ها',
            },
        ),
    ]
